sudo: false
language: node_js
node_js:
  - '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
- bower install
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - dist/jquery-cmdr.js
  - dist/jquery-cmdr.min.js
  skip_cleanup: true
  on:
    tags: true
    repo: cmdrjs/jquery-cmdrjs
cache:
  directories:
  - node_modules
  - bower_components
